Repository KrispyTech/airneis, pull requests merged in 2024-01, with the labels that each got.

#12 AIRNEIS-40: Updated the make file by adding docker commands and adding a help command
  Makefile
  docs/make/readme.md
Labels: documentation

#5 Added a documentation for the database model
  docs/database/readme.md
  docs/dive-in/2024/01/2024-01-08-model-database.md
Labels: documentation

#14 Add documentation to sign commits
  docs/security/commit-signing.md
Labels: documentation

#15 AIRNEIS-35 - Dive-In : Protect app secrets
  docs/dive-in/2024/01/2024-01-17-protect-app-secrets/2024-01-17-protect-app-secrets.md
  docs/dive-in/2024/01/2024-01-17-protect-app-secrets/Screenshot 2024-01-18 at 18.51.59.png
Labels: dive-in

#17 Airneis 35: Make HTTP Client
  back/lib/shared/httpclient/httpclient.go
  docs/back/http-client-golang.md
  docs/back/images/http_example.png
Labels: enhancement

#18 Airneis 35: Init Vault files and remove hello test files
  back/lib/shared/hello/hello.go
  back/lib/shared/hello/hello_test.go
  back/lib/shared/vault/vault.go
  back/lib/shared/vault/vault_test.go
Labels: enhancement

#19 Airneis 35: Init Config
  .gitignore
  back/.env.sample
  back/config/config.go
  back/config/default.yaml
  back/config/production.yaml
  back/config/staging.yaml
  back/go.mod
  back/go.sum
  back/main.go
Labels: enhancement

#25 New tooling : Github Reminder!
  tooling/github/pull-requets-reminder/.env.sample
  tooling/github/pull-requets-reminder/go.mod
  tooling/github/pull-requets-reminder/go.sum
  tooling/github/pull-requets-reminder/main.go
Labels: enhancement

#21 Airneis 35 : Vault Client
  .gitignore
  back/.env.sample
  back/config/config.go
  back/config/default.yaml
  back/go.mod
  back/go.sum
  back/lib/shared/httpclient/httpclient.go
  back/lib/shared/httpclient/httpclient_mock.go
  back/lib/shared/vault/vault.go
  back/lib/shared/vault/vault_test.go
  back/main.go
Labels: enhancement
