Repository KrispyTech/airneis, pull requests merged in 2024-03, with the labels that each got.

#59 AIRNEIS-59: Mobile navigation
  mobile/App.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/components/Header.jsx
  mobile/src/components/Page.jsx
  mobile/src/screens/CategoriesScreen.jsx
  mobile/src/screens/HomeScreen.jsx
  mobile/src/utils/constants/screens.js
Labels: enhancement, Ready for test, mobile, Priority

#64 Added a make ci command to run the ci locally
  Makefile
Labels: enhancement, Ready for test, CI/CD

#33 Dive in Gorm setup
  docs/dive-in/2024/02/2024-02-07:configure-gorm.md
  docs/dive-in/2024/02/img.png
Labels: documentation, dive-in, backend

#75 AIRNEIS-112 : Frontend HTTP API + Config bugfixes
  .gitignore
  back/Dockerfile
  back/pkg/config/config.go
  back/pkg/routes/categories.go
  back/pkg/routes/routes.go
  back/src/controllers/categories/GetCategoryById.go
  docker-compose-dev.yml
  front/.env.local.exemple
  front/package.json
  front/src/pages/api/hello.js
  front/src/pages/api/test/categoriesFunctions.js
  front/src/utils/config.js
  front/src/utils/constants.js
  front/src/utils/httpClient.js
  front/src/utils/services/CategoryServices.js
Labels: frontend, backend, Priority

#73 AIRNEIS-74 : Linter configuration for GoSec
  .github/workflows/go.yml
  back/.golangci.yml
Labels: enhancement, CI/CD, Priority

#77 AIRNEIS-114 - New + Rework : Add styling features to linter
  Makefile
  back/.golangci.yml
  back/lib/shared/helpers/convertStringToInt.go
  back/lib/shared/helpers/setStatusAndMessages.go
  back/lib/shared/helpers/strings.go
  back/lib/shared/httpclient/httpclient.go
  back/lib/shared/httpclient/httpclient_mock.go
  back/lib/shared/vault/vault.go
  back/pkg/config/config.go
  back/pkg/config/db.go
  back/pkg/config/types.go
  back/src/controllers/categories/CreateCategory.go
  back/src/controllers/categories/DeleteCategory.go
  back/src/controllers/categories/EditCategories.go
  back/src/controllers/categories/GetCategories.go
  back/src/controllers/categories/GetCategoryById.go
  back/src/controllers/categories/categories.go
  back/src/models/Address.go
  back/src/models/Category.go
  back/src/models/Order.go
  back/src/models/Product.go
  back/src/models/ProductImage.go
  back/src/models/User.go
  front/.env.local.exemple
Labels: backend, dependencies, Priority

#78 AIRNEIS-59: Display categories on mobile
  back/lib/shared/helpers/convertStringToInt.go
  back/lib/shared/helpers/strings.go
  back/src/controllers/categories/GetCategories.go
  back/src/controllers/categories/categories.go
  back/src/models/Category.go
  front/src/pages/api/test/categoriesFunctions.js
  mobile/.env.exemple
  mobile/App.js
  mobile/mobileConfig.js
  mobile/package.json
  mobile/src/components/Header.jsx
  mobile/src/components/Page.jsx
  mobile/src/components/ProductCard.jsx
  mobile/src/screens/CategoriesScreen.jsx
  mobile/src/screens/CategoryScreen.jsx
  mobile/src/screens/ErrorScreen.jsx
  mobile/src/screens/HomeScreen.jsx
  mobile/src/utils/categoriesServices.js
  mobile/src/utils/constants/apiRoutes.js
  mobile/src/utils/constants/errors.js
  mobile/src/utils/httpClient.js
Labels: backend, mobile

#82 Rework: Changed Product Model
  back/src/models/Product.go
  docs/database/readme.md
Labels: documentation, backend, go
