Repository KrispyTech/airneis, pull requests merged in 2024-02, with the labels that each got.

#26 Airneis 32 feature/configure docker env
  Makefile
  back/Dockerfile
  docker-compose-dev.yml
  docker-compose.yml
  front/Dockerfile
  front/package.json
Labels: enhancement

#31 Updated CI: an improved on front and called prettier on front and mobile
  .github/workflows/js.yml
  front/.prettierignore
Labels: enhancement, Ready for test, CI/CD

#34 Added conf files to Dockerfile back
  back/Dockerfile
Labels: enhancement, CI/CD

#38 Docs - Readme : Fix tracker link
  README.md
Labels: bug, documentation

#41 Add setup instructions on main README
  README.md
Labels: documentation, frontend, backend, mobile

#28 Coding Practices Backend
  docs/coding-practices.md
Labels: documentation, backend

#20 Docs: Tech Stack for Airneis
  docs/stacks/images/spa-mpa.png
  docs/stacks/tech-stack.md
Labels: documentation, product management

#40 Added front, back and mobile README
  back/README.md
  front/README.md
  mobile/README.md
Labels: documentation, frontend, backend, mobile

#36 Feature: setup Neon db connection
  .gitignore
  README.md
  back/config/config.go
  back/db/neon.go
  back/go.mod
  back/go.sum
  back/main.go
Labels: enhancement, backend

#42 setup/AIRNEIS-38: setup gorm inside of project
  back/config/config.go
  back/config/db.go
  back/go.mod
  back/go.sum
  back/main.go
Labels: Ready for test, backend
